# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1570, 905)
        Form.setMinimumSize(QtCore.QSize(1570, 905))
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 12, 1, 1)
        self.label_800 = QtWidgets.QLabel(self.widget_2)
        self.label_800.setMinimumSize(QtCore.QSize(1000, 60))
        self.label_800.setMaximumSize(QtCore.QSize(1500, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_800.setFont(font)
        self.label_800.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_800.setFrameShape(QtWidgets.QFrame.Box)
        self.label_800.setAlignment(QtCore.Qt.AlignCenter)
        self.label_800.setObjectName("label_800")
        self.gridLayout.addWidget(self.label_800, 3, 0, 1, 12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 10, 14, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 14, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 8, 0, 1, 1)
        self.label_reverse_val = QtWidgets.QLabel(self.widget_2)
        self.label_reverse_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_reverse_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_reverse_val.setFont(font)
        self.label_reverse_val.setObjectName("label_reverse_val")
        self.gridLayout.addWidget(self.label_reverse_val, 13, 2, 1, 4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 8, 9, 1, 1)
        self.label_pressure_800_val = QtWidgets.QLabel(self.widget_2)
        self.label_pressure_800_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_pressure_800_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_pressure_800_val.setFont(font)
        self.label_pressure_800_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pressure_800_val.setObjectName("label_pressure_800_val")
        self.gridLayout.addWidget(self.label_pressure_800_val, 2, 0, 1, 3)
        self.label_600_obr1 = QtWidgets.QLabel(self.widget_2)
        self.label_600_obr1.setMinimumSize(QtCore.QSize(1000, 60))
        self.label_600_obr1.setMaximumSize(QtCore.QSize(1500, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_600_obr1.setFont(font)
        self.label_600_obr1.setStyleSheet("background-color: rgb(170, 210, 255);")
        self.label_600_obr1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_600_obr1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_600_obr1.setObjectName("label_600_obr1")
        self.gridLayout.addWidget(self.label_600_obr1, 6, 0, 2, 12)
        self.label_500_obr2 = QtWidgets.QLabel(self.widget_2)
        self.label_500_obr2.setMinimumSize(QtCore.QSize(1000, 60))
        self.label_500_obr2.setMaximumSize(QtCore.QSize(1500, 60))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_500_obr2.setFont(font)
        self.label_500_obr2.setStyleSheet("background-color: rgb(170, 180, 255);")
        self.label_500_obr2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_500_obr2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_500_obr2.setObjectName("label_500_obr2")
        self.gridLayout.addWidget(self.label_500_obr2, 10, 0, 1, 12)
        self.label_nasosnya33km = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label_nasosnya33km.setFont(font)
        self.label_nasosnya33km.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nasosnya33km.setObjectName("label_nasosnya33km")
        self.gridLayout.addWidget(self.label_nasosnya33km, 0, 13, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 4, 0, 1, 1)
        self.label_pressure_600_val = QtWidgets.QLabel(self.widget_2)
        self.label_pressure_600_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_pressure_600_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_pressure_600_val.setFont(font)
        self.label_pressure_600_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pressure_600_val.setObjectName("label_pressure_600_val")
        self.gridLayout.addWidget(self.label_pressure_600_val, 5, 0, 1, 6)
        self.label_piket = QtWidgets.QLabel(self.widget_2)
        self.label_piket.setMinimumSize(QtCore.QSize(250, 25))
        self.label_piket.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label_piket.setFont(font)
        self.label_piket.setObjectName("label_piket")
        self.gridLayout.addWidget(self.label_piket, 0, 0, 1, 1)
        self.label_dy_500_val = QtWidgets.QLabel(self.widget_2)
        self.label_dy_500_val.setMinimumSize(QtCore.QSize(360, 240))
        self.label_dy_500_val.setMaximumSize(QtCore.QSize(360, 240))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_dy_500_val.setFont(font)
        self.label_dy_500_val.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_dy_500_val.setFrameShape(QtWidgets.QFrame.Box)
        self.label_dy_500_val.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_dy_500_val.setObjectName("label_dy_500_val")
        self.gridLayout.addWidget(self.label_dy_500_val, 7, 13, 4, 1)
        self.label_dy_600_val = QtWidgets.QLabel(self.widget_2)
        self.label_dy_600_val.setMinimumSize(QtCore.QSize(360, 240))
        self.label_dy_600_val.setMaximumSize(QtCore.QSize(360, 240))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_dy_600_val.setFont(font)
        self.label_dy_600_val.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_dy_600_val.setFrameShape(QtWidgets.QFrame.Box)
        self.label_dy_600_val.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_dy_600_val.setObjectName("label_dy_600_val")
        self.gridLayout.addWidget(self.label_dy_600_val, 3, 13, 4, 1)
        self.label_pressure_500_val = QtWidgets.QLabel(self.widget_2)
        self.label_pressure_500_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_pressure_500_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_pressure_500_val.setFont(font)
        self.label_pressure_500_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pressure_500_val.setObjectName("label_pressure_500_val")
        self.gridLayout.addWidget(self.label_pressure_500_val, 9, 0, 1, 3)
        self.label_temp_cold = QtWidgets.QLabel(self.widget_2)
        self.label_temp_cold.setMaximumSize(QtCore.QSize(270, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_temp_cold.setFont(font)
        self.label_temp_cold.setObjectName("label_temp_cold")
        self.gridLayout.addWidget(self.label_temp_cold, 14, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 11, 0, 1, 1)
        self.label_temp_air = QtWidgets.QLabel(self.widget_2)
        self.label_temp_air.setMinimumSize(QtCore.QSize(0, 0))
        self.label_temp_air.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_temp_air.setFont(font)
        self.label_temp_air.setObjectName("label_temp_air")
        self.gridLayout.addWidget(self.label_temp_air, 12, 0, 1, 3)
        self.label_timer = QtWidgets.QLabel(self.widget_2)
        self.label_timer.setMinimumSize(QtCore.QSize(840, 80))
        self.label_timer.setMaximumSize(QtCore.QSize(840, 80))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.label_timer.setFont(font)
        self.label_timer.setObjectName("label_timer")
        self.gridLayout.addWidget(self.label_timer, 16, 0, 1, 10)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 15, 0, 1, 1)
        self.label_reverse = QtWidgets.QLabel(self.widget_2)
        self.label_reverse.setMaximumSize(QtCore.QSize(345, 40))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label_reverse.setFont(font)
        self.label_reverse.setObjectName("label_reverse")
        self.gridLayout.addWidget(self.label_reverse, 13, 0, 1, 2)
        self.label_temp_cold_val = QtWidgets.QLabel(self.widget_2)
        self.label_temp_cold_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_temp_cold_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_temp_cold_val.setFont(font)
        self.label_temp_cold_val.setObjectName("label_temp_cold_val")
        self.gridLayout.addWidget(self.label_temp_cold_val, 14, 1, 1, 5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 1, 0, 1, 1)
        self.label_opc_resp = QtWidgets.QLabel(self.widget_2)
        self.label_opc_resp.setMinimumSize(QtCore.QSize(310, 25))
        self.label_opc_resp.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_opc_resp.setFont(font)
        self.label_opc_resp.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.label_opc_resp.setFrameShape(QtWidgets.QFrame.Box)
        self.label_opc_resp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opc_resp.setObjectName("label_opc_resp")
        self.gridLayout.addWidget(self.label_opc_resp, 16, 13, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 9, 10, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 12, 11, 1, 1)
        self.label_air_600_val = QtWidgets.QLabel(self.widget_2)
        self.label_air_600_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_air_600_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_air_600_val.setFont(font)
        self.label_air_600_val.setObjectName("label_air_600_val")
        self.gridLayout.addWidget(self.label_air_600_val, 5, 11, 1, 1)
        self.label_air_500_val = QtWidgets.QLabel(self.widget_2)
        self.label_air_500_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_air_500_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_air_500_val.setFont(font)
        self.label_air_500_val.setObjectName("label_air_500_val")
        self.gridLayout.addWidget(self.label_air_500_val, 9, 11, 1, 1)
        self.label_air_800_val = QtWidgets.QLabel(self.widget_2)
        self.label_air_800_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_air_800_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_air_800_val.setFont(font)
        self.label_air_800_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_air_800_val.setObjectName("label_air_800_val")
        self.gridLayout.addWidget(self.label_air_800_val, 2, 11, 1, 1)
        self.label_temp_800_val = QtWidgets.QLabel(self.widget_2)
        self.label_temp_800_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_temp_800_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_temp_800_val.setFont(font)
        self.label_temp_800_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_800_val.setObjectName("label_temp_800_val")
        self.gridLayout.addWidget(self.label_temp_800_val, 2, 7, 1, 1)
        self.label_temp_500_val = QtWidgets.QLabel(self.widget_2)
        self.label_temp_500_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_temp_500_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_temp_500_val.setFont(font)
        self.label_temp_500_val.setTextFormat(QtCore.Qt.AutoText)
        self.label_temp_500_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_500_val.setObjectName("label_temp_500_val")
        self.gridLayout.addWidget(self.label_temp_500_val, 9, 7, 1, 1)
        self.label_temp_air_val = QtWidgets.QLabel(self.widget_2)
        self.label_temp_air_val.setEnabled(True)
        self.label_temp_air_val.setMinimumSize(QtCore.QSize(200, 45))
        self.label_temp_air_val.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_temp_air_val.setFont(font)
        self.label_temp_air_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_air_val.setObjectName("label_temp_air_val")
        self.gridLayout.addWidget(self.label_temp_air_val, 12, 3, 1, 1)
        self.label_temp_600_val = QtWidgets.QLabel(self.widget_2)
        self.label_temp_600_val.setMinimumSize(QtCore.QSize(230, 45))
        self.label_temp_600_val.setMaximumSize(QtCore.QSize(230, 45))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_temp_600_val.setFont(font)
        self.label_temp_600_val.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_temp_600_val.setObjectName("label_temp_600_val")
        self.gridLayout.addWidget(self.label_temp_600_val, 5, 7, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_800.setText(_translate("Form", "800 (Подача)"))
        self.label_reverse_val.setText(_translate("Form", "0.00кгс/см2"))
        self.label_pressure_800_val.setText(_translate("Form", "0.00кгс/см2"))
        self.label_600_obr1.setText(_translate("Form", "600 (Обратка - 1)"))
        self.label_500_obr2.setText(_translate("Form", "500 (Обратка - 2)"))
        self.label_nasosnya33km.setText(_translate("Form", "Насосная 33км"))
        self.label_pressure_600_val.setText(_translate("Form", "0.00кгс/см2"))
        self.label_piket.setText(_translate("Form", "Пикет №1"))
        self.label_dy_500_val.setText(_translate("Form", "ДУ 500\n"
"\n"
"0.00кгс/см2"))
        self.label_dy_600_val.setText(_translate("Form", "ДУ 600\n"
"\n"
"0.00кгс/см2"))
        self.label_pressure_500_val.setText(_translate("Form", "0.00кгс/см2"))
        self.label_temp_cold.setText(_translate("Form", "Температура ХВ :"))
        self.label_temp_air.setText(_translate("Form", "Температура нар. возд. :"))
        self.label_timer.setText(_translate("Form", "тек.время"))
        self.label_reverse.setText(_translate("Form", "Обратный коллектор : "))
        self.label_temp_cold_val.setText(_translate("Form", "00.00°C"))
        self.label_opc_resp.setText(_translate("Form", "Опрос : ожидание..."))
        self.label_air_600_val.setText(_translate("Form", "0.00м3/ч"))
        self.label_air_500_val.setText(_translate("Form", "0.00м3/ч"))
        self.label_air_800_val.setText(_translate("Form", "0.00м3/ч"))
        self.label_temp_800_val.setText(_translate("Form", "00.00°C"))
        self.label_temp_500_val.setText(_translate("Form", "00.00°C"))
        self.label_temp_air_val.setText(_translate("Form", "00.00°C"))
        self.label_temp_600_val.setText(_translate("Form", "00.00°C"))
